### ISSUE TITLE
ERROR: for ctfd_ctfd_1  Cannot start service ctfd: failed to create task for container: 

### ISSUE THREAD

**Issue by diannaofengzi** [huangzheng2016/CTFd-docker#5]
出现如下错误

WARNING: The Docker Engine you're using is running in swarm mode.

Compose does not use swarm mode to deploy services to multiple nodes in a swarm. All containers will be scheduled on the current node.

To deploy your application across the swarm, use `docker stack deploy`.

Recreating ctfd_db_1    ... done
Recreating ctfd_frpc_1  ... done
Recreating ctfd_frps_1  ... done
Recreating ctfd_cache_1 ... done
Recreating ctfd_ctfd_1  ... error

ERROR: for ctfd_ctfd_1  Cannot start service ctfd: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "/opt/CTFd/docker-entrypoint.sh": permission denied: unknown

ERROR: for ctfd  Cannot start service ctfd: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "/opt/CTFd/docker-entrypoint.sh": permission denied: unknown
ERROR: Encountered errors while bringing up the project.

**Comment by diannaofengzi** [comment]
Attempting uninstall: redis
    Found existing installation: redis 4.4.4
    Uninstalling redis-4.4.4:
      Successfully uninstalled redis-4.4.4
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
botocore 1.16.26 requires urllib3<1.26,>=1.20; python_version != "3.4", but you have urllib3 1.26.17 which is incompatible.

**Comment by diannaofengzi** [comment]
Status: Downloaded newer image for nginx:stable
Creating ctfd_frps_1  ... done
Creating ctfd_db_1    ... done
Creating ctfd_frpc_1  ... done
Creating ctfd_cache_1 ... done
Creating ctfd_ctfd_1  ... done
Creating ctfd_nginx_1 ... done
Traceback (most recent call last):
  File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2345, in _wrap_pool_connect
    return fn()
  File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 304, in unique_connection
    return _ConnectionFairy._checkout(self)
  File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 778, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 495, in checkout
    rec = pool._do_get()
  File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 140, in _do_get
    self._dec_overflow()
  File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.raise_(
  File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 137, in _do_get
    return self._create_connection()
  File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 309, in _create_connection
    return _ConnectionRecord(self)
  File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 440, in __init__
    self.__connect(first_connect_check=True)
  File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.raise_(
  File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 656, in __connect
    connection = pool._invoke_creator(self)
  File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
  File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 490, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/opt/venv/lib/python3.9/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/opt/venv/lib/python3.9/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/opt/venv/lib/python3.9/site-packages/pymysql/connections.py", line 598, in connect
    self._get_server_information()
  File "/opt/venv/lib/python3.9/site-packages/pymysql/connections.py", line 975, in _get_server_information
    packet = self._read_packet()
  File "/opt/venv/lib/python3.9/site-packages/pymysql/connections.py", line 669, in _read_packet
    raise err.InternalError(
pymysql.err.InternalError: Packet sequence number wrong - got 1 expected 0

**Comment by diannaofengzi** [comment]
2830d28189bb   nginx:stable                "/docker-entrypoint.…"   12 minutes ago   Restarting (1) 32 seconds ago                                                                                                                      ctfd_nginx_1
be857a783464   ctfd_ctfd                   "/opt/CTFd/docker-en…"   12 minutes ago   Restarting (1) 15 seconds ago                                                                                                                      ctfd_ctfd_1


一直在Restarting

**Comment by huangzheng2016** [comment]
solved
